// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: book.proto

package org.tech.with.orkhan.demo;

public final class Book {
  private Book() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code Genre}
   */
  public enum Genre
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SCI_FI = 0;</code>
     */
    SCI_FI(0),
    /**
     * <code>FANTASY = 1;</code>
     */
    FANTASY(1),
    /**
     * <code>POETRY = 2;</code>
     */
    POETRY(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>SCI_FI = 0;</code>
     */
    public static final int SCI_FI_VALUE = 0;
    /**
     * <code>FANTASY = 1;</code>
     */
    public static final int FANTASY_VALUE = 1;
    /**
     * <code>POETRY = 2;</code>
     */
    public static final int POETRY_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Genre valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Genre forNumber(int value) {
      switch (value) {
        case 0: return SCI_FI;
        case 1: return FANTASY;
        case 2: return POETRY;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Genre>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Genre> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Genre>() {
            public Genre findValueByNumber(int number) {
              return Genre.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.tech.with.orkhan.demo.Book.getDescriptor().getEnumTypes().get(0);
    }

    private static final Genre[] VALUES = values();

    public static Genre valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Genre(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Genre)
  }

  public interface BookRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BookRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 bookId = 1;</code>
     * @return The bookId.
     */
    int getBookId();
  }
  /**
   * Protobuf type {@code BookRequest}
   */
  public  static final class BookRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:BookRequest)
      BookRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BookRequest.newBuilder() to construct.
    private BookRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BookRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new BookRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BookRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              bookId_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tech.with.orkhan.demo.Book.internal_static_BookRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tech.with.orkhan.demo.Book.internal_static_BookRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tech.with.orkhan.demo.Book.BookRequest.class, org.tech.with.orkhan.demo.Book.BookRequest.Builder.class);
    }

    public static final int BOOKID_FIELD_NUMBER = 1;
    private int bookId_;
    /**
     * <code>int32 bookId = 1;</code>
     * @return The bookId.
     */
    public int getBookId() {
      return bookId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (bookId_ != 0) {
        output.writeInt32(1, bookId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (bookId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, bookId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.tech.with.orkhan.demo.Book.BookRequest)) {
        return super.equals(obj);
      }
      org.tech.with.orkhan.demo.Book.BookRequest other = (org.tech.with.orkhan.demo.Book.BookRequest) obj;

      if (getBookId()
          != other.getBookId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BOOKID_FIELD_NUMBER;
      hash = (53 * hash) + getBookId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.tech.with.orkhan.demo.Book.BookRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tech.with.orkhan.demo.Book.BookRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tech.with.orkhan.demo.Book.BookRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tech.with.orkhan.demo.Book.BookRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tech.with.orkhan.demo.Book.BookRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tech.with.orkhan.demo.Book.BookRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tech.with.orkhan.demo.Book.BookRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.tech.with.orkhan.demo.Book.BookRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.tech.with.orkhan.demo.Book.BookRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.tech.with.orkhan.demo.Book.BookRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.tech.with.orkhan.demo.Book.BookRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.tech.with.orkhan.demo.Book.BookRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.tech.with.orkhan.demo.Book.BookRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BookRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BookRequest)
        org.tech.with.orkhan.demo.Book.BookRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.tech.with.orkhan.demo.Book.internal_static_BookRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.tech.with.orkhan.demo.Book.internal_static_BookRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.tech.with.orkhan.demo.Book.BookRequest.class, org.tech.with.orkhan.demo.Book.BookRequest.Builder.class);
      }

      // Construct using org.tech.with.orkhan.demo.Book.BookRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bookId_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.tech.with.orkhan.demo.Book.internal_static_BookRequest_descriptor;
      }

      @java.lang.Override
      public org.tech.with.orkhan.demo.Book.BookRequest getDefaultInstanceForType() {
        return org.tech.with.orkhan.demo.Book.BookRequest.getDefaultInstance();
      }

      @java.lang.Override
      public org.tech.with.orkhan.demo.Book.BookRequest build() {
        org.tech.with.orkhan.demo.Book.BookRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.tech.with.orkhan.demo.Book.BookRequest buildPartial() {
        org.tech.with.orkhan.demo.Book.BookRequest result = new org.tech.with.orkhan.demo.Book.BookRequest(this);
        result.bookId_ = bookId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.tech.with.orkhan.demo.Book.BookRequest) {
          return mergeFrom((org.tech.with.orkhan.demo.Book.BookRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.tech.with.orkhan.demo.Book.BookRequest other) {
        if (other == org.tech.with.orkhan.demo.Book.BookRequest.getDefaultInstance()) return this;
        if (other.getBookId() != 0) {
          setBookId(other.getBookId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.tech.with.orkhan.demo.Book.BookRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.tech.with.orkhan.demo.Book.BookRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int bookId_ ;
      /**
       * <code>int32 bookId = 1;</code>
       * @return The bookId.
       */
      public int getBookId() {
        return bookId_;
      }
      /**
       * <code>int32 bookId = 1;</code>
       * @param value The bookId to set.
       * @return This builder for chaining.
       */
      public Builder setBookId(int value) {
        
        bookId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 bookId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearBookId() {
        
        bookId_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:BookRequest)
    }

    // @@protoc_insertion_point(class_scope:BookRequest)
    private static final org.tech.with.orkhan.demo.Book.BookRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.tech.with.orkhan.demo.Book.BookRequest();
    }

    public static org.tech.with.orkhan.demo.Book.BookRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BookRequest>
        PARSER = new com.google.protobuf.AbstractParser<BookRequest>() {
      @java.lang.Override
      public BookRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BookRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BookRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BookRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.tech.with.orkhan.demo.Book.BookRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BookResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BookResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string title = 1;</code>
     * @return The title.
     */
    java.lang.String getTitle();
    /**
     * <code>string title = 1;</code>
     * @return The bytes for title.
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>.Genre genre = 2;</code>
     * @return The enum numeric value on the wire for genre.
     */
    int getGenreValue();
    /**
     * <code>.Genre genre = 2;</code>
     * @return The genre.
     */
    org.tech.with.orkhan.demo.Book.Genre getGenre();

    /**
     * <code>int32 price = 3;</code>
     * @return The price.
     */
    int getPrice();
  }
  /**
   * Protobuf type {@code BookResponse}
   */
  public  static final class BookResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:BookResponse)
      BookResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BookResponse.newBuilder() to construct.
    private BookResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BookResponse() {
      title_ = "";
      genre_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new BookResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BookResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              title_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              genre_ = rawValue;
              break;
            }
            case 24: {

              price_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tech.with.orkhan.demo.Book.internal_static_BookResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tech.with.orkhan.demo.Book.internal_static_BookResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tech.with.orkhan.demo.Book.BookResponse.class, org.tech.with.orkhan.demo.Book.BookResponse.Builder.class);
    }

    public static final int TITLE_FIELD_NUMBER = 1;
    private volatile java.lang.Object title_;
    /**
     * <code>string title = 1;</code>
     * @return The title.
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      }
    }
    /**
     * <code>string title = 1;</code>
     * @return The bytes for title.
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GENRE_FIELD_NUMBER = 2;
    private int genre_;
    /**
     * <code>.Genre genre = 2;</code>
     * @return The enum numeric value on the wire for genre.
     */
    public int getGenreValue() {
      return genre_;
    }
    /**
     * <code>.Genre genre = 2;</code>
     * @return The genre.
     */
    public org.tech.with.orkhan.demo.Book.Genre getGenre() {
      @SuppressWarnings("deprecation")
      org.tech.with.orkhan.demo.Book.Genre result = org.tech.with.orkhan.demo.Book.Genre.valueOf(genre_);
      return result == null ? org.tech.with.orkhan.demo.Book.Genre.UNRECOGNIZED : result;
    }

    public static final int PRICE_FIELD_NUMBER = 3;
    private int price_;
    /**
     * <code>int32 price = 3;</code>
     * @return The price.
     */
    public int getPrice() {
      return price_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTitleBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, title_);
      }
      if (genre_ != org.tech.with.orkhan.demo.Book.Genre.SCI_FI.getNumber()) {
        output.writeEnum(2, genre_);
      }
      if (price_ != 0) {
        output.writeInt32(3, price_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTitleBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, title_);
      }
      if (genre_ != org.tech.with.orkhan.demo.Book.Genre.SCI_FI.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, genre_);
      }
      if (price_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, price_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.tech.with.orkhan.demo.Book.BookResponse)) {
        return super.equals(obj);
      }
      org.tech.with.orkhan.demo.Book.BookResponse other = (org.tech.with.orkhan.demo.Book.BookResponse) obj;

      if (!getTitle()
          .equals(other.getTitle())) return false;
      if (genre_ != other.genre_) return false;
      if (getPrice()
          != other.getPrice()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getTitle().hashCode();
      hash = (37 * hash) + GENRE_FIELD_NUMBER;
      hash = (53 * hash) + genre_;
      hash = (37 * hash) + PRICE_FIELD_NUMBER;
      hash = (53 * hash) + getPrice();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.tech.with.orkhan.demo.Book.BookResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tech.with.orkhan.demo.Book.BookResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tech.with.orkhan.demo.Book.BookResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tech.with.orkhan.demo.Book.BookResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tech.with.orkhan.demo.Book.BookResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tech.with.orkhan.demo.Book.BookResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tech.with.orkhan.demo.Book.BookResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.tech.with.orkhan.demo.Book.BookResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.tech.with.orkhan.demo.Book.BookResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.tech.with.orkhan.demo.Book.BookResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.tech.with.orkhan.demo.Book.BookResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.tech.with.orkhan.demo.Book.BookResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.tech.with.orkhan.demo.Book.BookResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BookResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BookResponse)
        org.tech.with.orkhan.demo.Book.BookResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.tech.with.orkhan.demo.Book.internal_static_BookResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.tech.with.orkhan.demo.Book.internal_static_BookResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.tech.with.orkhan.demo.Book.BookResponse.class, org.tech.with.orkhan.demo.Book.BookResponse.Builder.class);
      }

      // Construct using org.tech.with.orkhan.demo.Book.BookResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        title_ = "";

        genre_ = 0;

        price_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.tech.with.orkhan.demo.Book.internal_static_BookResponse_descriptor;
      }

      @java.lang.Override
      public org.tech.with.orkhan.demo.Book.BookResponse getDefaultInstanceForType() {
        return org.tech.with.orkhan.demo.Book.BookResponse.getDefaultInstance();
      }

      @java.lang.Override
      public org.tech.with.orkhan.demo.Book.BookResponse build() {
        org.tech.with.orkhan.demo.Book.BookResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.tech.with.orkhan.demo.Book.BookResponse buildPartial() {
        org.tech.with.orkhan.demo.Book.BookResponse result = new org.tech.with.orkhan.demo.Book.BookResponse(this);
        result.title_ = title_;
        result.genre_ = genre_;
        result.price_ = price_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.tech.with.orkhan.demo.Book.BookResponse) {
          return mergeFrom((org.tech.with.orkhan.demo.Book.BookResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.tech.with.orkhan.demo.Book.BookResponse other) {
        if (other == org.tech.with.orkhan.demo.Book.BookResponse.getDefaultInstance()) return this;
        if (!other.getTitle().isEmpty()) {
          title_ = other.title_;
          onChanged();
        }
        if (other.genre_ != 0) {
          setGenreValue(other.getGenreValue());
        }
        if (other.getPrice() != 0) {
          setPrice(other.getPrice());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.tech.with.orkhan.demo.Book.BookResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.tech.with.orkhan.demo.Book.BookResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object title_ = "";
      /**
       * <code>string title = 1;</code>
       * @return The title.
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string title = 1;</code>
       * @return The bytes for title.
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string title = 1;</code>
       * @param value The title to set.
       * @return This builder for chaining.
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string title = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTitle() {
        
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>string title = 1;</code>
       * @param value The bytes for title to set.
       * @return This builder for chaining.
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        title_ = value;
        onChanged();
        return this;
      }

      private int genre_ = 0;
      /**
       * <code>.Genre genre = 2;</code>
       * @return The enum numeric value on the wire for genre.
       */
      public int getGenreValue() {
        return genre_;
      }
      /**
       * <code>.Genre genre = 2;</code>
       * @param value The enum numeric value on the wire for genre to set.
       * @return This builder for chaining.
       */
      public Builder setGenreValue(int value) {
        genre_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.Genre genre = 2;</code>
       * @return The genre.
       */
      public org.tech.with.orkhan.demo.Book.Genre getGenre() {
        @SuppressWarnings("deprecation")
        org.tech.with.orkhan.demo.Book.Genre result = org.tech.with.orkhan.demo.Book.Genre.valueOf(genre_);
        return result == null ? org.tech.with.orkhan.demo.Book.Genre.UNRECOGNIZED : result;
      }
      /**
       * <code>.Genre genre = 2;</code>
       * @param value The genre to set.
       * @return This builder for chaining.
       */
      public Builder setGenre(org.tech.with.orkhan.demo.Book.Genre value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        genre_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Genre genre = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearGenre() {
        
        genre_ = 0;
        onChanged();
        return this;
      }

      private int price_ ;
      /**
       * <code>int32 price = 3;</code>
       * @return The price.
       */
      public int getPrice() {
        return price_;
      }
      /**
       * <code>int32 price = 3;</code>
       * @param value The price to set.
       * @return This builder for chaining.
       */
      public Builder setPrice(int value) {
        
        price_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 price = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPrice() {
        
        price_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:BookResponse)
    }

    // @@protoc_insertion_point(class_scope:BookResponse)
    private static final org.tech.with.orkhan.demo.Book.BookResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.tech.with.orkhan.demo.Book.BookResponse();
    }

    public static org.tech.with.orkhan.demo.Book.BookResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BookResponse>
        PARSER = new com.google.protobuf.AbstractParser<BookResponse>() {
      @java.lang.Override
      public BookResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BookResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BookResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BookResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.tech.with.orkhan.demo.Book.BookResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BookRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BookRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BookResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BookResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nbook.proto\"\035\n\013BookRequest\022\016\n\006bookId\030\001 " +
      "\001(\005\"C\n\014BookResponse\022\r\n\005title\030\001 \001(\t\022\025\n\005ge" +
      "nre\030\002 \001(\0162\006.Genre\022\r\n\005price\030\003 \001(\005*,\n\005Genr" +
      "e\022\n\n\006SCI_FI\020\000\022\013\n\007FANTASY\020\001\022\n\n\006POETRY\020\00225" +
      "\n\013BookService\022&\n\007getBook\022\014.BookRequest\032\r" +
      ".BookResponseB\033\n\031org.tech.with.orkhan.de" +
      "mob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_BookRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BookRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BookRequest_descriptor,
        new java.lang.String[] { "BookId", });
    internal_static_BookResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_BookResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BookResponse_descriptor,
        new java.lang.String[] { "Title", "Genre", "Price", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
